openapi: 3.0.1
info:
  title: Identity.SubscribedSkus
  version: v1.0-Beta
servers:
  - url: https://graph.microsoft.com/Beta/
    description: Core
paths:
  /subscribedSkus:
    get:
      tags:
        - subscribedSkus.subscribedSku
      summary: Get entities from subscribedSkus
      operationId: subscribedSkus.subscribedSku_ListSubscribedSku
      parameters:
        - $ref: '#/components/parameters/search'
        - name: $orderby
          in: query
          description: Order items by property values
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
                - capabilityStatus
                - capabilityStatus desc
                - consumedUnits
                - consumedUnits desc
                - prepaidUnits
                - prepaidUnits desc
                - servicePlans
                - servicePlans desc
                - skuId
                - skuId desc
                - skuPartNumber
                - skuPartNumber desc
                - appliesTo
                - appliesTo desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - capabilityStatus
                - consumedUnits
                - prepaidUnits
                - servicePlans
                - skuId
                - skuPartNumber
                - appliesTo
              type: string
      responses:
        '200':
          description: Retrieved entities
          content:
            application/json:
              schema:
                title: Collection of subscribedSku
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.subscribedSku'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    post:
      tags:
        - subscribedSkus.subscribedSku
      summary: Add new entity to subscribedSkus
      operationId: subscribedSkus.subscribedSku_CreateSubscribedSku
      requestBody:
        description: New entity
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.subscribedSku'
        required: true
      responses:
        '201':
          description: Created entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.subscribedSku'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/subscribedSkus/{subscribedSku-id}':
    get:
      tags:
        - subscribedSkus.subscribedSku
      summary: Get entity from subscribedSkus by key
      operationId: subscribedSkus.subscribedSku_GetSubscribedSku
      parameters:
        - name: subscribedSku-id
          in: path
          description: 'key: subscribedSku-id of subscribedSku'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: subscribedSku
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - capabilityStatus
                - consumedUnits
                - prepaidUnits
                - servicePlans
                - skuId
                - skuPartNumber
                - appliesTo
              type: string
      responses:
        '200':
          description: Retrieved entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.subscribedSku'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    patch:
      tags:
        - subscribedSkus.subscribedSku
      summary: Update entity in subscribedSkus
      operationId: subscribedSkus.subscribedSku_UpdateSubscribedSku
      parameters:
        - name: subscribedSku-id
          in: path
          description: 'key: subscribedSku-id of subscribedSku'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: subscribedSku
      requestBody:
        description: New property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.subscribedSku'
        required: true
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    delete:
      tags:
        - subscribedSkus.subscribedSku
      summary: Delete entity from subscribedSkus
      operationId: subscribedSkus.subscribedSku_DeleteSubscribedSku
      parameters:
        - name: subscribedSku-id
          in: path
          description: 'key: subscribedSku-id of subscribedSku'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: subscribedSku
        - name: If-Match
          in: header
          description: ETag
          schema:
            type: string
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
components:
  schemas:
    microsoft.graph.subscribedSku:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: subscribedSku
          type: object
          properties:
            capabilityStatus:
              type: string
              nullable: true
            consumedUnits:
              maximum: 2147483647
              minimum: -2147483648
              type: integer
              format: int32
              nullable: true
            prepaidUnits:
              $ref: '#/components/schemas/microsoft.graph.licenseUnitsDetail'
            servicePlans:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.servicePlanInfo'
            skuId:
              pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
              type: string
              format: uuid
              nullable: true
            skuPartNumber:
              type: string
              nullable: true
            appliesTo:
              type: string
              nullable: true
      example:
        id: string (identifier)
        capabilityStatus: string
        consumedUnits: integer
        prepaidUnits:
          '@odata.type': microsoft.graph.licenseUnitsDetail
        servicePlans:
          - '@odata.type': microsoft.graph.servicePlanInfo
        skuId: string
        skuPartNumber: string
        appliesTo: string
    microsoft.graph.entity:
      title: entity
      type: object
      properties:
        id:
          type: string
      example:
        id: string (identifier)
    microsoft.graph.licenseUnitsDetail:
      title: licenseUnitsDetail
      type: object
      properties:
        enabled:
          maximum: 2147483647
          minimum: -2147483648
          type: integer
          format: int32
          nullable: true
        suspended:
          maximum: 2147483647
          minimum: -2147483648
          type: integer
          format: int32
          nullable: true
        warning:
          maximum: 2147483647
          minimum: -2147483648
          type: integer
          format: int32
          nullable: true
      example:
        enabled: integer
        suspended: integer
        warning: integer
    microsoft.graph.servicePlanInfo:
      title: servicePlanInfo
      type: object
      properties:
        servicePlanId:
          pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
          type: string
          format: uuid
          nullable: true
        servicePlanName:
          type: string
          nullable: true
        provisioningStatus:
          type: string
          nullable: true
        appliesTo:
          type: string
          nullable: true
      example:
        servicePlanId: string
        servicePlanName: string
        provisioningStatus: string
        appliesTo: string
    odata.error:
      required:
        - error
      type: object
      properties:
        error:
          $ref: '#/components/schemas/odata.error.main'
    odata.error.main:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/odata.error.detail'
        innererror:
          type: object
          description: The structure of this object is service-specific
    odata.error.detail:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
  responses:
    error:
      description: error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/odata.error'
  parameters:
    search:
      name: $search
      in: query
      description: Search items by search phrases
      schema:
        type: string
  securitySchemes:
    azureaadv2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
          tokenUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token
          scopes: { }
security:
  - azureaadv2: [ ]