openapi: 3.0.1
info:
  title: Identity.Organization
  version: v1.0-StagingBeta
servers:
  - url: https://graph.microsoft.com/StagingBeta/
    description: Core
paths:
  /organization:
    get:
      tags:
        - organization.organization
      summary: Get entities from organization
      operationId: organization.organization_ListOrganization
      parameters:
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/search'
        - name: $orderby
          in: query
          description: Order items by property values
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
                - deletedDateTime
                - deletedDateTime desc
                - assignedPlans
                - assignedPlans desc
                - businessPhones
                - businessPhones desc
                - city
                - city desc
                - country
                - country desc
                - countryLetterCode
                - countryLetterCode desc
                - createdDateTime
                - createdDateTime desc
                - displayName
                - displayName desc
                - isMultipleDataLocationsForServicesEnabled
                - isMultipleDataLocationsForServicesEnabled desc
                - marketingNotificationEmails
                - marketingNotificationEmails desc
                - onPremisesLastSyncDateTime
                - onPremisesLastSyncDateTime desc
                - onPremisesSyncEnabled
                - onPremisesSyncEnabled desc
                - postalCode
                - postalCode desc
                - preferredLanguage
                - preferredLanguage desc
                - privacyProfile
                - privacyProfile desc
                - provisionedPlans
                - provisionedPlans desc
                - securityComplianceNotificationMails
                - securityComplianceNotificationMails desc
                - securityComplianceNotificationPhones
                - securityComplianceNotificationPhones desc
                - state
                - state desc
                - street
                - street desc
                - technicalNotificationMails
                - technicalNotificationMails desc
                - verifiedDomains
                - verifiedDomains desc
                - mobileDeviceManagementAuthority
                - mobileDeviceManagementAuthority desc
                - certificateConnectorSetting
                - certificateConnectorSetting desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - deletedDateTime
                - assignedPlans
                - businessPhones
                - city
                - country
                - countryLetterCode
                - createdDateTime
                - displayName
                - isMultipleDataLocationsForServicesEnabled
                - marketingNotificationEmails
                - onPremisesLastSyncDateTime
                - onPremisesSyncEnabled
                - postalCode
                - preferredLanguage
                - privacyProfile
                - provisionedPlans
                - securityComplianceNotificationMails
                - securityComplianceNotificationPhones
                - state
                - street
                - technicalNotificationMails
                - verifiedDomains
                - mobileDeviceManagementAuthority
                - certificateConnectorSetting
                - brandings
                - certificateBasedAuthConfiguration
                - extensions
              type: string
      responses:
        '200':
          description: Retrieved entities
          content:
            application/json:
              schema:
                title: Collection of organization
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.organization'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    post:
      tags:
        - organization.organization
      summary: Add new entity to organization
      operationId: organization.organization_CreateOrganization
      requestBody:
        description: New entity
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.organization'
        required: true
      responses:
        '201':
          description: Created entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.organization'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/organization/{organization-id}':
    get:
      tags:
        - organization.organization
      summary: Get entity from organization by key
      operationId: organization.organization_GetOrganization
      parameters:
        - name: organization-id
          in: path
          description: 'key: organization-id of organization'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: organization
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - deletedDateTime
                - assignedPlans
                - businessPhones
                - city
                - country
                - countryLetterCode
                - createdDateTime
                - displayName
                - isMultipleDataLocationsForServicesEnabled
                - marketingNotificationEmails
                - onPremisesLastSyncDateTime
                - onPremisesSyncEnabled
                - postalCode
                - preferredLanguage
                - privacyProfile
                - provisionedPlans
                - securityComplianceNotificationMails
                - securityComplianceNotificationPhones
                - state
                - street
                - technicalNotificationMails
                - verifiedDomains
                - mobileDeviceManagementAuthority
                - certificateConnectorSetting
                - brandings
                - certificateBasedAuthConfiguration
                - extensions
              type: string
      responses:
        '200':
          description: Retrieved entity
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.organization'
          links:
            brandings:
              operationId: organization.organization.GetOrganization
              parameters:
                id: $request.path.id
            certificateBasedAuthConfiguration:
              operationId: organization.organization.GetOrganization
              parameters:
                id: $request.path.id
            extensions:
              operationId: organization.organization.GetOrganization
              parameters:
                id: $request.path.id
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    patch:
      tags:
        - organization.organization
      summary: Update entity in organization
      operationId: organization.organization_UpdateOrganization
      parameters:
        - name: organization-id
          in: path
          description: 'key: organization-id of organization'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: organization
      requestBody:
        description: New property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.organization'
        required: true
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    delete:
      tags:
        - organization.organization
      summary: Delete entity from organization
      operationId: organization.organization_DeleteOrganization
      parameters:
        - name: organization-id
          in: path
          description: 'key: organization-id of organization'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: organization
        - name: If-Match
          in: header
          description: ETag
          schema:
            type: string
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/organization/{organization-id}/brandings':
    get:
      tags:
        - organization.organizationalBranding
      summary: Get brandings from organization
      operationId: organization_ListBrandings
      parameters:
        - name: organization-id
          in: path
          description: 'key: organization-id of organization'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: organization
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
                - backgroundColor
                - backgroundColor desc
                - backgroundImage
                - backgroundImage desc
                - bannerLogo
                - bannerLogo desc
                - locale
                - locale desc
                - signInPageText
                - signInPageText desc
                - squareLogo
                - squareLogo desc
                - usernameHintText
                - usernameHintText desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - backgroundColor
                - backgroundImage
                - bannerLogo
                - locale
                - signInPageText
                - squareLogo
                - usernameHintText
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                title: Collection of organizationalBranding
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.organizationalBranding'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    post:
      tags:
        - organization.organizationalBranding
      summary: Create new navigation property to brandings for organization
      operationId: organization_CreateBrandings
      parameters:
        - name: organization-id
          in: path
          description: 'key: organization-id of organization'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: organization
      requestBody:
        description: New navigation property
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.organizationalBranding'
        required: true
      responses:
        '201':
          description: Created navigation property.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.organizationalBranding'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/organization/{organization-id}/brandings/{organizationalBranding-id}':
    get:
      tags:
        - organization.organizationalBranding
      summary: Get brandings from organization
      operationId: organization_GetBrandings
      parameters:
        - name: organization-id
          in: path
          description: 'key: organization-id of organization'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: organization
        - name: organizationalBranding-id
          in: path
          description: 'key: organizationalBranding-id of organizationalBranding'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: organizationalBranding
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - backgroundColor
                - backgroundImage
                - bannerLogo
                - locale
                - signInPageText
                - squareLogo
                - usernameHintText
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.organizationalBranding'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    patch:
      tags:
        - organization.organizationalBranding
      summary: Update the navigation property brandings in organization
      operationId: organization_UpdateBrandings
      parameters:
        - name: organization-id
          in: path
          description: 'key: organization-id of organization'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: organization
        - name: organizationalBranding-id
          in: path
          description: 'key: organizationalBranding-id of organizationalBranding'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: organizationalBranding
      requestBody:
        description: New navigation property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.organizationalBranding'
        required: true
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/organization/{organization-id}/certificateBasedAuthConfiguration':
    get:
      tags:
        - organization.certificateBasedAuthConfiguration
      summary: Get certificateBasedAuthConfiguration from organization
      operationId: organization_ListCertificateBasedAuthConfiguration
      parameters:
        - name: organization-id
          in: path
          description: 'key: organization-id of organization'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: organization
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
                - certificateAuthorities
                - certificateAuthorities desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - certificateAuthorities
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                title: Collection of certificateBasedAuthConfiguration
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.certificateBasedAuthConfiguration'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/organization/{organization-id}/certificateBasedAuthConfiguration/{certificateBasedAuthConfiguration-id}':
    get:
      tags:
        - organization.certificateBasedAuthConfiguration
      summary: Get certificateBasedAuthConfiguration from organization
      operationId: organization_GetCertificateBasedAuthConfiguration
      parameters:
        - name: organization-id
          in: path
          description: 'key: organization-id of organization'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: organization
        - name: certificateBasedAuthConfiguration-id
          in: path
          description: 'key: certificateBasedAuthConfiguration-id of certificateBasedAuthConfiguration'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: certificateBasedAuthConfiguration
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - certificateAuthorities
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.certificateBasedAuthConfiguration'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/organization/{organization-id}/extensions':
    get:
      tags:
        - organization.extension
      summary: Get extensions from organization
      operationId: organization_ListExtensions
      parameters:
        - name: organization-id
          in: path
          description: 'key: organization-id of organization'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: organization
        - $ref: '#/components/parameters/top'
        - $ref: '#/components/parameters/skip'
        - $ref: '#/components/parameters/search'
        - $ref: '#/components/parameters/filter'
        - $ref: '#/components/parameters/count'
        - name: $orderby
          in: query
          description: Order items by property values
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
                - id desc
              type: string
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                title: Collection of extension
                type: object
                properties:
                  value:
                    type: array
                    items:
                      $ref: '#/components/schemas/microsoft.graph.extension'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    post:
      tags:
        - organization.extension
      summary: Create new navigation property to extensions for organization
      operationId: organization_CreateExtensions
      parameters:
        - name: organization-id
          in: path
          description: 'key: organization-id of organization'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: organization
      requestBody:
        description: New navigation property
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.extension'
        required: true
      responses:
        '201':
          description: Created navigation property.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.extension'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/organization/{organization-id}/extensions/{extension-id}':
    get:
      tags:
        - organization.extension
      summary: Get extensions from organization
      operationId: organization_GetExtensions
      parameters:
        - name: organization-id
          in: path
          description: 'key: organization-id of organization'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: organization
        - name: extension-id
          in: path
          description: 'key: extension-id of extension'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: extension
        - name: $select
          in: query
          description: Select properties to be returned
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - id
              type: string
        - name: $expand
          in: query
          description: Expand related entities
          style: simple
          schema:
            uniqueItems: true
            type: array
            items:
              enum:
                - '*'
              type: string
      responses:
        '200':
          description: Retrieved navigation property
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/microsoft.graph.extension'
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
    patch:
      tags:
        - organization.extension
      summary: Update the navigation property extensions in organization
      operationId: organization_UpdateExtensions
      parameters:
        - name: organization-id
          in: path
          description: 'key: organization-id of organization'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: organization
        - name: extension-id
          in: path
          description: 'key: extension-id of extension'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: extension
      requestBody:
        description: New navigation property values
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/microsoft.graph.extension'
        required: true
      responses:
        '204':
          description: Success
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: operation
  '/organization/{organization-id}/microsoft.graph.setMobileDeviceManagementAuthority':
    post:
      tags:
        - organization.Actions
      summary: Invoke action setMobileDeviceManagementAuthority
      operationId: organization_setMobileDeviceManagementAuthority
      parameters:
        - name: organization-id
          in: path
          description: 'key: organization-id of organization'
          required: true
          schema:
            type: string
          x-ms-docs-key-type: organization
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                maximum: 2147483647
                minimum: -2147483648
                type: integer
                format: int32
        default:
          $ref: '#/components/responses/error'
      x-ms-docs-operation-type: action
components:
  schemas:
    microsoft.graph.organization:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.directoryObject'
        - title: organization
          type: object
          properties:
            assignedPlans:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.assignedPlan'
            businessPhones:
              type: array
              items:
                type: string
            city:
              type: string
              nullable: true
            country:
              type: string
              nullable: true
            countryLetterCode:
              type: string
              nullable: true
            createdDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              format: date-time
              nullable: true
            displayName:
              type: string
              nullable: true
            isMultipleDataLocationsForServicesEnabled:
              type: boolean
              nullable: true
            marketingNotificationEmails:
              type: array
              items:
                type: string
            onPremisesLastSyncDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              format: date-time
              nullable: true
            onPremisesSyncEnabled:
              type: boolean
              nullable: true
            postalCode:
              type: string
              nullable: true
            preferredLanguage:
              type: string
              nullable: true
            privacyProfile:
              $ref: '#/components/schemas/microsoft.graph.privacyProfile'
            provisionedPlans:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.provisionedPlan'
            securityComplianceNotificationMails:
              type: array
              items:
                type: string
            securityComplianceNotificationPhones:
              type: array
              items:
                type: string
            state:
              type: string
              nullable: true
            street:
              type: string
              nullable: true
            technicalNotificationMails:
              type: array
              items:
                type: string
            verifiedDomains:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.verifiedDomain'
            mobileDeviceManagementAuthority:
              $ref: '#/components/schemas/microsoft.graph.mdmAuthority'
            certificateConnectorSetting:
              $ref: '#/components/schemas/microsoft.graph.certificateConnectorSetting'
            brandings:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.organizationalBranding'
            certificateBasedAuthConfiguration:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.certificateBasedAuthConfiguration'
            extensions:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.extension'
          description: The organization resource represents an instance of global settings and resources which operate and are provisioned at the tenant-level.
      example:
        id: string (identifier)
        deletedDateTime: string (timestamp)
        assignedPlans:
          - '@odata.type': microsoft.graph.assignedPlan
        businessPhones:
          - string
        city: string
        country: string
        countryLetterCode: string
        createdDateTime: string (timestamp)
        displayName: string
        isMultipleDataLocationsForServicesEnabled: true
        marketingNotificationEmails:
          - string
        onPremisesLastSyncDateTime: string (timestamp)
        onPremisesSyncEnabled: true
        postalCode: string
        preferredLanguage: string
        privacyProfile:
          '@odata.type': microsoft.graph.privacyProfile
        provisionedPlans:
          - '@odata.type': microsoft.graph.provisionedPlan
        securityComplianceNotificationMails:
          - string
        securityComplianceNotificationPhones:
          - string
        state: string
        street: string
        technicalNotificationMails:
          - string
        verifiedDomains:
          - '@odata.type': microsoft.graph.verifiedDomain
        mobileDeviceManagementAuthority:
          '@odata.type': microsoft.graph.mdmAuthority
        certificateConnectorSetting:
          '@odata.type': microsoft.graph.certificateConnectorSetting
        brandings:
          - '@odata.type': microsoft.graph.organizationalBranding
        certificateBasedAuthConfiguration:
          - '@odata.type': microsoft.graph.certificateBasedAuthConfiguration
        extensions:
          - '@odata.type': microsoft.graph.extension
    microsoft.graph.organizationalBranding:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: organizationalBranding
          type: object
          properties:
            backgroundColor:
              type: string
              nullable: true
            backgroundImage:
              type: string
              format: base64url
            bannerLogo:
              type: string
              format: base64url
            locale:
              type: string
              nullable: true
            signInPageText:
              type: string
              nullable: true
            squareLogo:
              type: string
              format: base64url
            usernameHintText:
              type: string
              nullable: true
      example:
        id: string (identifier)
        backgroundColor: string
        backgroundImage: string
        bannerLogo: string
        locale: string
        signInPageText: string
        squareLogo: string
        usernameHintText: string
    microsoft.graph.certificateBasedAuthConfiguration:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: certificateBasedAuthConfiguration
          type: object
          properties:
            certificateAuthorities:
              type: array
              items:
                $ref: '#/components/schemas/microsoft.graph.certificateAuthority'
      example:
        id: string (identifier)
        certificateAuthorities:
          - '@odata.type': microsoft.graph.certificateAuthority
    microsoft.graph.extension:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: extension
          type: object
      example:
        id: string (identifier)
    microsoft.graph.directoryObject:
      allOf:
        - $ref: '#/components/schemas/microsoft.graph.entity'
        - title: directoryObject
          type: object
          properties:
            deletedDateTime:
              pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
              type: string
              format: date-time
              nullable: true
          description: Represents an Azure Active Directory object. The directoryObject type is the base type for many other directory entity types.
      example:
        id: string (identifier)
        deletedDateTime: string (timestamp)
    microsoft.graph.assignedPlan:
      title: assignedPlan
      type: object
      properties:
        assignedDateTime:
          pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
          type: string
          format: date-time
          nullable: true
        capabilityStatus:
          type: string
          nullable: true
        service:
          type: string
          nullable: true
        servicePlanId:
          pattern: '^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$'
          type: string
          format: uuid
          nullable: true
      example:
        assignedDateTime: string (timestamp)
        capabilityStatus: string
        service: string
        servicePlanId: string
    microsoft.graph.privacyProfile:
      title: privacyProfile
      type: object
      properties:
        contactEmail:
          type: string
          nullable: true
        statementUrl:
          type: string
          nullable: true
      example:
        contactEmail: string
        statementUrl: string
    microsoft.graph.provisionedPlan:
      title: provisionedPlan
      type: object
      properties:
        capabilityStatus:
          type: string
          nullable: true
        provisioningStatus:
          type: string
          nullable: true
        service:
          type: string
          nullable: true
      example:
        capabilityStatus: string
        provisioningStatus: string
        service: string
    microsoft.graph.verifiedDomain:
      title: verifiedDomain
      type: object
      properties:
        capabilities:
          type: string
          nullable: true
        isDefault:
          type: boolean
          nullable: true
        isInitial:
          type: boolean
          nullable: true
        name:
          type: string
          nullable: true
        type:
          type: string
          nullable: true
      example:
        capabilities: string
        isDefault: true
        isInitial: true
        name: string
        type: string
    microsoft.graph.mdmAuthority:
      title: mdmAuthority
      enum:
        - unknown
        - intune
        - sccm
        - office365
      type: string
    microsoft.graph.certificateConnectorSetting:
      title: certificateConnectorSetting
      type: object
      properties:
        status:
          maximum: 2147483647
          minimum: -2147483648
          type: integer
          description: Certificate connector status
          format: int32
        certExpiryTime:
          pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
          type: string
          description: Certificate expire time
          format: date-time
        enrollmentError:
          type: string
          description: Certificate connector enrollment error
          nullable: true
        lastConnectorConnectionTime:
          pattern: '^[0-9]{4,}-(0[1-9]|1[012])-(0[1-9]|[12][0-9]|3[01])T([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9]([.][0-9]{1,12})?(Z|[+-][0-9][0-9]:[0-9][0-9])$'
          type: string
          description: Last time certificate connector connected
          format: date-time
        connectorVersion:
          type: string
          description: Version of certificate connector
          nullable: true
        lastUploadVersion:
          type: integer
          description: Version of last uploaded certificate connector
          format: int64
      example:
        status: integer
        certExpiryTime: string (timestamp)
        enrollmentError: string
        lastConnectorConnectionTime: string (timestamp)
        connectorVersion: string
        lastUploadVersion: integer
    microsoft.graph.entity:
      title: entity
      type: object
      properties:
        id:
          type: string
      example:
        id: string (identifier)
    microsoft.graph.certificateAuthority:
      title: certificateAuthority
      type: object
      properties:
        isRootAuthority:
          type: boolean
        certificateRevocationListUrl:
          type: string
          nullable: true
        deltaCertificateRevocationListUrl:
          type: string
          nullable: true
        certificate:
          type: string
          format: base64url
        issuer:
          type: string
        issuerSki:
          type: string
      example:
        isRootAuthority: true
        certificateRevocationListUrl: string
        deltaCertificateRevocationListUrl: string
        certificate: string
        issuer: string
        issuerSki: string
    odata.error:
      required:
        - error
      type: object
      properties:
        error:
          $ref: '#/components/schemas/odata.error.main'
    odata.error.main:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
        details:
          type: array
          items:
            $ref: '#/components/schemas/odata.error.detail'
        innererror:
          type: object
          description: The structure of this object is service-specific
    odata.error.detail:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: string
        message:
          type: string
        target:
          type: string
  responses:
    error:
      description: error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/odata.error'
  parameters:
    top:
      name: $top
      in: query
      description: Show only the first n items
      schema:
        minimum: 0
        type: integer
      example: 50
    search:
      name: $search
      in: query
      description: Search items by search phrases
      schema:
        type: string
    skip:
      name: $skip
      in: query
      description: Skip the first n items
      schema:
        minimum: 0
        type: integer
    filter:
      name: $filter
      in: query
      description: Filter items by property values
      schema:
        type: string
    count:
      name: $count
      in: query
      description: Include count of items
      schema:
        type: boolean
  securitySchemes:
    azureaadv2:
      type: oauth2
      flows:
        authorizationCode:
          authorizationUrl: https://login.microsoftonline.com/common/oauth2/v2.0/authorize
          tokenUrl: https://login.microsoftonline.com/common/oauth2/v2.0/token
          scopes: { }
security:
  - azureaadv2: [ ]